# Generated by Django 5.0.6 on 2024-07-09 05:07

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("carNumber", models.CharField(max_length=30)),
                ("carOwner", models.CharField(max_length=30)),
                ("carOwnerNumber", models.CharField(max_length=10)),
                ("date", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="Parking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wingName", models.CharField(max_length=30)),
            ],
        ),
    ]
