# Generated by Django 5.0.6 on 2024-07-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cardetail_parkingspot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='wingName',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('C1', 'C1'), ('C2', 'C2')], max_length=30),
        ),
    ]
