# Generated by Django 5.0.6 on 2024-07-09 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cardetail_parkedwingname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetail',
            name='parkingSpot',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.parking'),
        ),
        migrations.AlterField(
            model_name='parking',
            name='wingName',
            field=models.CharField(max_length=30),
        ),
    ]
