# Generated by Django 5.0.6 on 2024-07-10 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_ownername_cardetail_owner_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parking',
            old_name='isAvailable',
            new_name='is_available',
        ),
    ]
