# Generated by Django 5.0.6 on 2024-07-10 06:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_parkingdetail_vehicle_has_left_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetail',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
