# Generated by Django 5.0.6 on 2024-07-10 06:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_cardetail_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingdetail",
            name="vehicle_arrived_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="parkingdetail",
            name="vehicle_left_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
