# Generated by Django 5.0.6 on 2024-07-11 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_parkingdetail_vehicle_arrived_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "owner_name_profile",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_name_profile",
                        to="core.cardetail",
                    ),
                ),
                (
                    "owner_number_profile",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_number_profile",
                        to="core.cardetail",
                    ),
                ),
                (
                    "vehicle_number_profile",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_number_profile",
                        to="core.cardetail",
                    ),
                ),
                (
                    "vehicle_type_profile",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_type_profile",
                        to="core.cardetail",
                    ),
                ),
            ],
        ),
    ]
