# Generated by Django 5.0.6 on 2024-07-16 09:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_owner_name_cardetail_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerprofile',
            name='owner_name_profile',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='owner_number_profile',
        ),
        migrations.RemoveField(
            model_name='parkingdetail',
            name='vehicle_number',
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='number_profile',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='owned_car',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cardetail'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='owner_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='owner_gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parkingdetail',
            name='vehicles',
            field=models.ManyToManyField(blank=True, related_name='parking_details', to='core.cardetail'),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='vehicle_number_profile',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='vehicle_type_profile',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
