# Generated by Django 5.0.6 on 2024-07-11 08:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_owner_name_cardetail_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='owner_address',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='owner_gender',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='owner_number_profile',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='vehicle_number_profile',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='vehicle_type_profile',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
