# Generated by Django 5.0.6 on 2024-07-11 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_ownerprofile_owner_address_ownerprofile_owner_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownerprofile',
            old_name='owner_number_profile',
            new_name='number_profile',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='owner_name_profile',
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='owned_car',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cardetail'),
        ),
    ]
