# Generated by Django 5.0.6 on 2024-07-12 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_rename_owner_number_profile_ownerprofile_number_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardetail',
            old_name='parking_wing',
            new_name='parking_wing_view',
        ),
    ]
