# Generated by Django 5.0.6 on 2024-07-12 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_rename_parking_wing_cardetail_parking_wing_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardetail',
            old_name='parking_wing_view',
            new_name='parking_wing',
        ),
    ]
