# Generated by Django 5.0.6 on 2024-07-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_rename_parking_wing_view_cardetail_parking_wing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingdetail',
            name='vehicle_number',
        ),
        migrations.AddField(
            model_name='parkingdetail',
            name='vehicle_number',
            field=models.ManyToManyField(blank=True, related_name='car', to='core.cardetail'),
        ),
    ]
