# Generated by Django 5.0.6 on 2024-07-12 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_parkingdetail_vehicle_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingdetail',
            old_name='vehicle_number',
            new_name='vehicles',
        ),
    ]
