# Generated by Django 5.0.6 on 2024-07-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_rename_vehicle_number_parkingdetail_vehicles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingdetail',
            name='vehicles',
            field=models.ManyToManyField(blank=True, related_name='CarDetail', to='core.cardetail'),
        ),
    ]
