# Generated by Django 5.0.6 on 2024-07-15 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_parkingdetail_vehicles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingdetail',
            name='vehicles',
            field=models.ManyToManyField(blank=True, related_name='parking_details', to='core.cardetail'),
        ),
    ]
