# Generated by Django 5.0.6 on 2024-07-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wing_name', models.CharField(max_length=50)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
