# Generated by Django 5.0.6 on 2024-07-16 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_customuser_is_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleowner',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
