# Generated by Django 5.0.7 on 2024-07-22 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_vehicleowner_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleowner',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
