# Generated by Django 5.0.7 on 2024-07-24 05:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0010_parkingreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingreport',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='parkingreport',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='parkingreport',
            name='description',
        ),
        migrations.RemoveField(
            model_name='parkingreport',
            name='title',
        ),
        migrations.AddField(
            model_name='parkingreport',
            name='parking_wing',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkingreport',
            name='vehicle_arrived_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='parkingreport',
            name='vehicle_arrived_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='parkingreport',
            name='vehicle_has_left',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingreport',
            name='vehicle_left_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parkingreport',
            name='vehicle_left_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parkingreport',
            name='vehicles',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
