# Generated by Django 5.0.7 on 2024-07-24 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0011_remove_parkingreport_cost_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParkingReport',
        ),
    ]
