# Generated by Django 4.2.14 on 2024-07-31 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0012_delete_parkingreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='wing_name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parking',
            name='wing_name_ne',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
