# Generated by Django 4.2.14 on 2024-08-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0015_remove_comment_end_offset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='whole_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='x1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='x2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='y1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='y2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
