# Generated by Django 4.2.14 on 2024-08-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0017_document_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
