# Generated by Django 4.2.14 on 2024-08-22 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0023_comment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
        migrations.RemoveField(
            model_name='document',
            name='image',
        ),
    ]
